INSERT INTO WALLET(ID, CASH_AMOUNT, BONUS_AMOUNT)VALUES(101,250,200)
INSERT INTO PLAYER(PLAYER_ID, NAME, USER_NAME, PASSWORD, ROLE_CODE, WALLET_ID)VALUES(10,'John doe','johndoe','john@123', 'PLAYER', 101)

INSERT INTO WALLET(ID, CASH_AMOUNT, BONUS_AMOUNT)VALUES(102,50,0)
INSERT INTO PLAYER(PLAYER_ID, NAME, USER_NAME, PASSWORD, ROLE_CODE, WALLET_ID)VALUES(11,'Jane Doe','janedoe','jane@123', 'PLAYER', 102)

INSERT INTO WALLET(ID, CASH_AMOUNT, BONUS_AMOUNT)VALUES(103,100,100)
INSERT INTO PLAYER(PLAYER_ID, NAME, USER_NAME, PASSWORD, ROLE_CODE, WALLET_ID)VALUES(12,'Scott Parker','scottparker','scott@123', 'PLAYER', 103)

INSERT INTO WALLET(ID, CASH_AMOUNT, BONUS_AMOUNT)VALUES(104,100,100)
INSERT INTO PLAYER(PLAYER_ID, NAME, USER_NAME, PASSWORD, ROLE_CODE, WALLET_ID)VALUES(13,'Jason Parker','jasonparker','jason@123', 'ADMIN', 104)
